<a href="https://colab.research.google.com/github/debjit-1004/NNfromZero/blob/main/neural_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#modifying three neurons with 4 inputs ...only one layer
import numpy as np
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]

biases=[2,3,0.5]

output=np.dot(weights,inputs) + biases
print(output)

[4.8   1.21  2.385]


In [ ]:
#modifying one neuron with 4 input only one layer
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(weights,inputs) + bias
print(output)

4.8


In [ ]:
#two layers i.e one hidden layer one input layer one output layer implementation
#modifying three neurons with 4 inputs ...only one layer
import numpy as np
#inputs in batch
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]

biases=[2,3,0.5]


weights2=[
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
]
biases2=[-1,2,-0.5]



layer1_outputs=np.dot(inputs,np.array(weights).T) + biases
print("layer1_outputs:\n",layer1_outputs)

layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T) + biases2
print("layer2_outputs:\n",layer2_outputs)


layer1_outputs:
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
layer2_outputs:
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
import numpy as np
np.random.seed(0)
#inputs in batch
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases


layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)



[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [ ]:
!pip install nnfs

import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

#inputs in batch
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]

X,y=spiral_data(100,3)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)


layer1=Layer_Dense(2,5)
activation1=Activation_ReLU()

layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)





[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

In [ ]:
import numpy as np
np.random.seed(0)
#inputs in batch
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]

inputs=[0,2,-1,3.3,-2.7,1.1,2,2,-100]

output=[]

for i in inputs:
  output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2, 2, 0]


In [ ]:
#sigmoid activation function
import math
layer_outputs=[4.8,1.21,2.385]
#E=2.718281828
E=math.e

for output in layer_outputs:
    print(1/(1+math.exp(-output)))

0.9918374288468401
0.7702989490466019
0.9156763035785255


In [1]:
import numpy as np
import math
layer_outputs=[4.8,1.21,2.385]
#E=2.718281828
E=math.e
# exp_values=[]
# for output in layer_outputs:
#     exp_values.append(E**output)
# print(exp_values)
exp_values=np.exp(layer_outputs)
# print(exp_values)
# norm_base=sum(exp_values)
# norm_values=[]
# for value in exp_values:
#     norm_values.append(value/norm_base)
# print(norm_values)
# print(sum(norm_values))

norm_values=exp_values/np.sum(exp_values) #for sum in 2d array we need to specify axis = 1 for row sum ...axis=0 for column sum and use keepdims=True
print(norm_values)
print(sum(norm_values))

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [2]:
!pip install nnfs

import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

#inputs in batch


class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_softmax():
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities

X,y=spiral_data(100,3)

dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2=Activation_softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)


print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [3]:
#catagorical cross entropy
import math
softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]
loss=-math.log(softmax_output[0])
print(loss)

0.35667494393873245


In [4]:
#implementing loss
import numpy as np
softmax_output=np.array([[0.7,0.1,0.2],
                        [0.1,0.5,0.4],
                        [0.02,0.9,0.08]])
class_targets=[0,1,1]
print(softmax_output[[0,1,2],class_targets])
print(np.mean(-np.log(softmax_output[range(len(softmax_output)),class_targets])))


[0.7 0.5 0.9]
0.38506088005216804


In [5]:
!pip install nnfs

import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()




class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities

class Loss:
  def calculate(self,output,y):
    sample_losses=self.forward(output,y)
    data_loss=np.mean(sample_losses)
    return data_loss

class Loss_CatagoricalCrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples=len(y_pred)
    y_pred_clipped=np.clip(y_pred,1e-7,1-1e-7)
    if len(y_true.shape)==1:
      correct_confidences=y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences=np.sum(y_pred_clipped*y_true,axis=1)
    negative_log_likelihoods=-np.log(correct_confidences)
    return negative_log_likelihoods



X,y=spiral_data(100,3)

dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2=Activation_softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)


print(activation2.output[:5])

loss_function=Loss_CatagoricalCrossentropy()
loss=loss_function.calculate(activation2.output,y)
print("loss:",loss)


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
loss: 1.098445


In [ ]:
#backpropagation